### ISSUE TITLE
`import claspy` not working after following recommended install

### ISSUE THREAD

**Issue by jfcann** [ermshaua/claspy#1]
This looks like a cool TSS package, but something seems to be wrong with the install instructions the time of writing.

Install via `pip` seems to work 👍 , but then `import claspy` fails.

MWE here: [test-install-claspy](https://www.kaggle.com/code/jagofc/test-install-claspy?scriptVersionId=122558503)

I've also tried locally with the same outcome.

Is there something I'm missing?

**Comment by ermshaua** [comment]
Thanks for mentioning this issue. I'll take a look at it. Strangely, it downloads all versions and then installs the wrong one:
`Successfully installed claspy-0.1.0`

**Comment by jfcann** [comment]
Awesome, thanks @ermshaua.

**Comment by ermshaua** [comment]
@jfcann I fixed this issue in version 0.1.6 by relaxing the matplotlib dependencies, that made Kaggle struggle. You should be able to use claspy after removing the old version and installing the newest one. Please let me know if it works for you!

Cheers, Arik

**Comment by jfcann** [comment]
@ermshaua - great stuff - thank you for the rapid fix!  
Test run [here](https://www.kaggle.com/code/jagofc/test-install-claspy?scriptVersionId=122657205).
