### ISSUE TITLE
Incorrect Change Point Prediction

### ISSUE THREAD

**Issue by aceg00** [ermshaua/claspy#10]
I tried using a code for time series segmentation, but the results I got were incorrect. I'm not sure why they're wrong - it might be because this code isn't suitable for my situation? I've taken a screenshot of the results.

![output](https://github.com/user-attachments/assets/98ad5193-3047-4354-9a5c-ed5ed1b8c31a)

**Comment by ermshaua** [comment]
Hi! At which time points do you expect change points? You can change the hyper-parameters of ClaSP to align it with your expectations. Here is a [notebook](https://github.com/ermshaua/claspy/blob/main/claspy/notebooks/clasp_configuration.ipynb) on how to do that.

**Comment by aceg00** [comment]
Hello! I have marked on the graph where I believe the change points should be located. I tried using distance="euclidean distance" and provided the correct segment number, n_segment=10, with validation=None. However, this didn't help much, as it still only detected one change point.
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/ea61b37a-2101-473a-b1e2-2a405197fee3">

**Comment by ermshaua** [comment]
Ok, I suggest you set the window size manually. Try low values like 5, 10, 15, 20. Maybe this helps. Let me know.
