### ISSUE TITLE
Segmentation of 2D time series

### ISSUE THREAD

**Issue by kageazusa** [ermshaua/claspy#4]
I am thinking of segmentation of trajectories of moving objects, i.e., 2D time series.
In the example of the Cricket data, it seems that the time series is 1D.
`dataset, window_size, true_cps, time_series = load_tssb_dataset(names=("CricketX",)).iloc[0,:]`
Is it possible to analyze 2D time series with claspy?

**Comment by ermshaua** [comment]
Sorry for the late reply, @kageazusa. I was on holiday until yesterday. No, currently claspy only supports 1D time series. However, we are currently researching multivariate segmentation approaches and will integrate them into claspy in the future. 

For now, you can e.g. segment every dimension of your time series separately and merge the resulting CPs one after the other using a function similar to BinaryClaSPSegmentation._cp_is_valid.
